<a href="https://colab.research.google.com/github/kaif22mohammed/Data-science-learning/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd
import sklearn

In [ ]:
df = pd.read_csv(r'https://raw.githubusercontent.com/nursnaaz/DataSciencewithPractical/main/11.%20Linear%20Regression-2/sample_lr.csv')

In [ ]:
df

x  y
0  1  1
1  3  2
2  4  5
3  6  6

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x = df.x

In [ ]:
x

0    1
1    3
2    4
3    6
Name: x, dtype: int64

In [ ]:
y = df.y

In [ ]:
y

0    1
1    2
2    5
3    6
Name: y, dtype: int64

In [ ]:
X = np.array(x)
y = np.array(y)

In [ ]:
model = LinearRegression()

In [ ]:
X = X.reshape(-1,1)
y = y.reshape(-1,1)

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
y_pred = model.predict(X)

In [ ]:
y_pred

array([[0.80769231],
       [2.96153846],
       [4.03846154],
       [6.19230769]])

In [ ]:
from sklearn.metrics import mean_squared_error , mean_absolute_error , mean_absolute_percentage_error , r2_score

In [ ]:
mean_squared_error(y,y_pred)

0.4807692307692307

In [ ]:
mean_absolute_error(y,y_pred)

0.5769230769230766

In [ ]:
mean_absolute_percentage_error(y,y_pred)

0.22435897435897417

In [ ]:
r2_score(y,y_pred)

0.8868778280542986

In [ ]:
model.coef_

array([[1.07692308]])

In [ ]:
model.intercept_

array([-0.26923077])

In [ ]:
#y = mx +c

In [ ]:
1.07692308*X+-0.26923077

array([[0.80769231],
       [2.96153847],
       [4.03846155],
       [6.19230771]])